### ISSUE TITLE
About pod installation 

### ISSUE THREAD

**Issue by NutanNiraula** [markgravity/nimble-survey#17]
Hi, thank you for your code submission. I tried to run the app but could not install the pods, it seems you are using local pods in your application. Could you please include them with the project or host them online and update the podspec please?

![Screen Shot 2020-11-04 at 3 07 57 PM](https://user-images.githubusercontent.com/46071848/98085174-871f0800-1eaf-11eb-83b6-98aaf0bdc477.png)

Meanwhile I will be looking at the code base, I will open further issues based on what I find in your codebase, some of them will be change request while most of the issues will focus on discussion about your design decisions so as to understand you better. Please feel free to discuss about your ideas and decisions openly, it will help me in gauging you. From my initial look you seem to have put some good effort in your submission, I will try to open some issues to kick off discussion based on my initial impressions.

**Comment by markgravity** [comment]
Hi @NutanNiraula, sorry I updated the pod file. Please check out the newest commit

**Comment by NutanNiraula** [comment]
Hmm, did you try to run pod install. I am still getting dependency errors. Please resolve this in next commit.
![Screen Shot 2020-11-05 at 12 56 27 PM](https://user-images.githubusercontent.com/46071848/98203285-5221bc80-1f66-11eb-9e0f-2543bf3ddcf8.png)

**Comment by markgravity** [comment]
Yea, It works normally on my end, I think you should run `pod update`, I guess your pod repo is older than me.
Updated:  I added `Pods` into the repo, so now you can just build the app normally 👍
